name = "CenterIndexedArrays"
uuid = "46a7138f-0d70-54e1-8ada-fb8296f91f24"
authors = ["Tim Holy <tim.holy@gmail.com>"]
version = "0.2.0"

[deps]
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
OffsetArrays = "6fe1bfb0-de20-5000-8ca7-80f57d26f881"

[compat]
Interpolations = "0.11, 0.12"
OffsetArrays = "0.10, 0.11, 1"
julia = "1"

[extras]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Random", "Test"]
